# Generated by Django 4.0.5 on 2022-06-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_image_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
