# Generated by Django 4.0.5 on 2022-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_image_options_remove_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='reaction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
