# Generated by Django 4.0.5 on 2022-06-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_customuser_profile_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
